### ISSUE TITLE
Nothing happens after launching.

### ISSUE THREAD

**Issue by tildethinexxbisense** [genki-angel/discord-data-parser#2]
I'm on Mac OS and after launching the executable for Mac, I see a button that says "Click to import data". But nothing happens after clicking it. Even dragging and dropping the data package doesn't work.

**Comment by genki-angel** [comment]
Hello,

Could you provide what version of macOS you are running? Thanks.

**Comment by genki-angel** [comment]
This issue has been fixed in the latest release.
