### ISSUE TITLE
It says "IMPORTING DATA..." and doesn't go forward at all

### ISSUE THREAD

**Issue by BlurryLens** [genki-angel/discord-data-parser#5]
Hey there, genki! Thank you so much for creating this parser. Surely it's useful and I am needing it, but I am not being able to do so:

When I select the package.zip file, it says "Importing data..." and everything stays the same. I tried running it as administrator to no avail, and left it running both times for quite a good amount of time.

Tried older versions, they also gave the same message of "Loading data..." forever.

I'm not sure what to do now, I'd love to know how to fix this!

Thank you for the help and best regards
![04c6d9f84e9045a7a7e268aa74624c31](https://user-images.githubusercontent.com/109534984/179538222-0a148a59-b588-49e3-974b-51d74e401a14.png)
![10d82310849d8b0454acd2e9cabff891](https://user-images.githubusercontent.com/109534984/179538230-eb406b59-fc8d-4562-ba49-e3245b35f4c5.png)
!

**Comment by genki-angel** [comment]
Hello! could I ask how big your data package is? and how much RAM you have installed into your computer? thanks.

**Comment by RandomExport5** [comment]
Hello there!
Sorry I had opened a similiar ticket that you closed about an hour ago. I didn't get the chance to reply since I didn't check my mail to it but I have been facing the same issue. My RAM is 6GB and the package size is 656 MB.
Thanks!

**Comment by genki-angel** [comment]
Sorry for my late replies, could you check if there is a .log file in the app directory?

**Comment by genki-angel** [comment]
This seems to be an issue with importing the full data zip on systems with lower resources, I will add a second import option which should avoid this issue.
